### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by Zardoz89**
Requires pthreads lib to be linked

### CODE REVIEW

**Comment by adam4813** [comment]
Is it -lpthread or should it just be pthreasd?

**Comment by Zardoz89** [comment]
On my system is "-lpthread" . I did a typo on the commit message

**Comment by adam4813** [comment]
OK merged after I make sure windows is good which I expect it to be.

**Comment by Zardoz89** [comment]
I close this, the other solution suggested by Paultech works fine (ate least on Linux) and looks better.

**Pull request closed without merging**
